name: Test

on:
  push:
    branches:
      - master
    worrkflow_dispatch:

    jobs:
      log_message:
        runs-on: ubuntu-latest
        steps:
        - name: Log 
          run: echo "The workflow is working!"